# Generated by Django 3.1 on 2021-04-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='year',
            field=models.IntegerField(default=2000),
        ),
    ]
