# Generated by Django 3.1 on 2021-04-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_films_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='posterUrl',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='films',
            name='rating',
            field=models.CharField(default='', max_length=100),
        ),
    ]
