# Generated by Django 3.1 on 2021-04-08 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='username',
        ),
    ]
