# Generated by Django 3.1 on 2021-04-09 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210408_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='username',
            new_name='password',
        ),
    ]
