# Generated by Django 3.1 on 2021-04-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210409_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='genres',
            field=models.CharField(default='', max_length=100),
        ),
    ]
