# Generated by Django 3.1 on 2021-04-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_users_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='genres',
        ),
        migrations.AddField(
            model_name='films',
            name='genres',
            field=models.CharField(default='', max_length=100),
        ),
    ]
