# Generated by Django 3.1 on 2021-04-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210409_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='actors',
            field=models.IntegerField(default=123),
        ),
        migrations.AddField(
            model_name='films',
            name='director',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='films',
            name='images',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='films',
            name='plot',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='films',
            name='runtime',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='films',
            name='trailer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='films',
            name='rating',
            field=models.FloatField(default=4.3),
        ),
    ]
