# Generated by Django 3.1 on 2021-04-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210409_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='actors',
            field=models.CharField(default='', max_length=100),
        ),
    ]
