# Generated by Django 3.1 on 2021-04-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210410_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('type', models.IntegerField(default=2000)),
                ('movies', models.IntegerField(default=2000)),
                ('description', models.TextField(default='', max_length=2000)),
                ('image', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
