# Generated by Django 3.1 on 2021-04-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210411_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='movies',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='persons',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
