# Generated by Django 3.1 on 2021-04-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210411_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='director',
            field=models.IntegerField(default=1),
        ),
    ]
