# Generated by Django 3.1 on 2021-04-24 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210411_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1)),
                ('movie_id', models.IntegerField(default=1)),
                ('review_id', models.IntegerField(default=1)),
                ('review_text', models.TextField(default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1)),
                ('movie_id', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
