# Generated by Django 3.1 on 2021-04-25 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210424_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='rating',
        ),
    ]
