# Generated by Django 3.1 on 2021-04-25 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_reviews_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user_id', 'movie_id')},
        ),
    ]
