# Generated by Django 3.1 on 2021-04-25 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20210425_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='num_of_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='films',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
